print('Hello World')
print('Let me introduce myself')
print('My name is Andi Hidayat')
print('I am 33 years old')
print('I live in Garut')
print('i love to do with Adobe Illustrator and do coding with Python')
print('Thank you')